{{ if .Values.hpa.enabled }}
{{ if and (eq .Capabilities.KubeVersion.Major &quot;1&quot;) (ge .Capabilities.KubeVersion.Minor &quot;8&quot;) }}
apiVersion: autoscaling/v2beta1
{{ else }}
apiVersion: autoscaling/v2alpha1
{{ end }}
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Chart.Name }}-hpa-policy"
  namespace: 
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: "{{ .Chart.Name }}-deployment"
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.metrics.cpu.targetAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.hpa.metrics.memory.targetAverageUtilization }}
{{ end }}